import os
from dotenv import load_dotenv

load_dotenv()

# =========================
# API KEYS
# =========================
PEXELS_API_KEY = os.getenv("PEXELS_API_KEY")
PIXABAY_API_KEY = os.getenv("PIXABAY_API_KEY")
UNSPLASH_ACCESS_KEY = os.getenv("UNSPLASH_ACCESS_KEY")
NYPL_API_KEY = os.getenv("NYPL_API_KEY")
EUROPEANA_API_KEY = os.getenv("EUROPEANA_API_KEY")
SMITHSONIAN_API_KEY = os.getenv("SMITHSONIAN_API_KEY")

# Additional sources
FLICKR_API_KEY = os.getenv("FLICKR_API_KEY")

# =========================
# GLOBAL SETTINGS
# =========================
REQUEST_DELAY = 1.2  # seconds (IMPORTANT)
MAX_WORKERS = 6
WATERMARK_THRESHOLD = 0.5

# =========================
# BUCKET QUERIES (ADVANCED)
# =========================

BUCKET_QUERIES = {

    "01_people_portraits": [
        "Indian woman portrait",
        "Indian elderly man face",
        "Rajasthani people",
        "Indian traditional dress portrait",
        "Indian village woman portrait",
        "Indian man turban portrait",
        "Indian child portrait",
        "indian tribal",
        "indian farmer",
        "indian artisan",
        "indian dancer portrait",
    ],
    "02_clothing_textiles": [
        "Indian saree silk",
        "Banarasi fabric",
        "phulkari embroidery",
        "Indian weaving handloom",
        "Indian textile jewelry",
        "Kanchipuram silk saree",
        "bandhani",
        "Indian block print fabric",
        "Indian traditional textile",

    ],
    "03_architecture": [
        "Hindu temple architecture",
        "Rajasthan fort",
        "Mughal monument",
        "Indian palace architecture",
        "Indian mosque monument",
        "South Indian temple gopuram",
        "dwarka temple architecture",
        "somnath temple architecture",
        "ajanta ellora caves architecture",
        "taj mahal architecture",
        "qutub minar",
        "raigad fort",
        "red fort delhi",
        "golconda fort",
        "fatehpur sikri",
        "hawa mahal",
        "mysore palace",
        "charminar",
        "india gate",
        "gateway of india",
        "humayun's tomb",
        "sanchi stupa",
        "konark sun temple",
        "khajuraho temples",
        "meenakshi temple",
        "somnath temple",
        "sun temple odisha",
        "ajanta caves",
        "ellora caves",
        " brihadeeswarar temple",
        "sri ranganathaswamy temple",
        "sanchi stupa",
        "konark sun temple",
        "khajuraho temples",
        "mahablipuram temples",
      
    ],
    "04_landscape_nature": [
        "Kerala backwaters",
        "Himalaya landscape",
        "Thar desert",
        "Indian mountains rivers forests",
        "Kerala backwaters",
        "Indian beaches landscape",
        "Indian forests nature",
        "desert landscape India",
        "Western Ghats landscape",
        "Sundarbans mangrove forest",
        "Valley of Flowers",
        "Rann of Kutch",
        "Coorg landscape",
        "Himalayan mountain landscape",
        "Indian river landscape",
        "Indian waterfall landscape",
        "ganges river landscape",
        "brahmaputra river landscape",
        "sundarbans mangrove forest",
        "indian monsoon landscape",
        "kerela",
        "ooty",
        "munnar",
        "coorg",
        "darjeeling",
        "sikkim",
        "manali"
    ],
    "05_urban_street": [
        "Mumbai street market",
        "Delhi bazaar",
        "Indian rickshaw",
        "Indian city streets",
        "Indian traffic market shops",
        "Indian urban street life",
        "ahmedabad kalupur market",
        "chennai marina beach",
        "kolkata howrah bridge",
        "varanasi ghats",
        "jaipur city palace",
        "hyderabad charminar",
        "riverfront road ahmedabad",
        "mg road bangalore",
        "cg road pune",
        "sg highway delhi",
        "sg highway ahmedabad",
    ],
    "06_rural_village": [
        "Indian village life",
        "paddy field farmer",
        "rural India",
        "Indian farming village",
        "Indian mud houses village",
        "Indian rural agriculture",
        "Indian village market",
        "Indian village children",
        "crops harvesting rural India",
        "water buffalo rural India",
        "Indian village festival",
        "Indian village wedding",
        "Indian village artisans",
        "Indian village crafts",
        "Indian",
        "Indian village landscape",
        "Indian village road",
        "Indian village school",
        "Indian village pond",
        "Indian village temple",
        "Indian village livestock",
        "Indian village",




    ],
    "07_food_drink": [
        "Indian thali food",
        "masala dosa",
        "Indian street food chaat",
        "Indian biryani",
        "Indian chai",
        "Indian sweets",
        "pasta",
        "mango lassi",
        "Indian curry",
        "maggie noodles",
        "Indian snacks",
        "dosa",
        "chaas",
        "paneer tikka",
        "chole kulche",
        "kaju katli",
        "jalebi",
        "gulab jamun",
        "rasgulla",
        "Indian food platter",
        "samosa",

        "delhi chaat",
        "hyderabad biryani",
        "mumbai vada pav",
        "kolkata mishti doi",
        "indian food market",
        "surti undhiyu",
        "gujarati thali",
        "punjabi food",
        "south indian food",
        "rajasthani food",
        "rajma chawal",
        "indian food street",


    ],
    "08_festivals_rituals": [
        "Holi festival colors",
        "Indian wedding ceremony",
        "Durga Puja",
        "Diwali celebration India",
        "Indian puja ritual",
        "Indian dance performance",
        "Navratri festival",
        "Ganesh Chaturthi festival",
        "Indian religious procession",
        "gudipuja festival",
        "onam festival",
        "lohri festival",
        "karva chauth festival",
        "makar sankranti festival",
        "chath puja festival",
        "durga puja festival",
    ],
    "09_objects_artifacts": [
        "Indian brass handicraft",
        "sitar instrument",
        "Indian pottery",
        "Indian artifacts",
        "Indian musical instruments",
        "Indian brass object",
        "Indian wooden artifact",
        "Indian traditional jewelry",
        "Indian bronze sculpture",
        "Indian terracotta art",
        "Indian handloom textile artifact",
        "Indian tribal artifact",
        "Indian religious artifact",
        "Indian folk art object",
        "Indian contemporary art object",
        "Indian decorative art object",
        
    ],
    "10_animals_wildlife": [
        "Bengal tiger",
        "Indian elephant",
        "peacock India",
        "Indian monkeys",
        "Indian cows",
        "Indian wildlife",
        "Indian birds",
        "lion India",
        "gir lion",
        "indian snake",
        "deer",
        "alligator",
        "leopard",
        "rhino",
        "Indian wildlife",
        "bears",
        "Indian butterflies",
        "Indian reptiles",
        "Indian aquatic animals",
        "Indian insects",
        "Indian amphibians",
        "Indian marine life",
        "Indian forest animals",
    ],
    "11_art_design": [
        "Madhubani painting",
        "Warli art",
        "Indian rangoli design",
        "Indian paintings murals",
        "Madhubani painting",
        "Indian wall mural art",
        "Indian folk art",
        "Indian tribal art",
        "Indian contemporary art",
        "Indian abstract art",
        "Indian geometric pattern",
    ],
    "12_abstract_texture": [
        "Indian textile pattern",
        "jali stone lattice",
        "kolam design",
        "Indian block print texture",
        "Indian motif texture",
        "Indian abstract texture",
        "Indian geometric texture",
        "Indian traditional pattern",
        "Indian decorative texture",
        'Indian architectural texture',
        'Indian art texture',
        "Indian cultural texture",
        "Indian fabric texture",
        "Indian wall texture",
        "Indian floor texture",
        "Indian ceiling texture",
        "Indian surface texture",
        "Indian background texture",
        "Indian abstract pattern",
        "Indian design texture",
        "Indian textile design",
        "Indian tile pattern",
        "Indian mosaic pattern",
        "Indian embroidery pattern",
        "Indian wood carving pattern",
        "Indian stone carving pattern",
        "Indian metalwork pattern",
        "Indian pottery pattern",
        "Indian rangoli pattern",
        "Indian kolam pattern",
        "Indian jali pattern",
        "Indian mehndi pattern",
        "Indian tattoo pattern",
        "Indian henna pattern",
    ],
}